version: '3'
services:
   web:
      image: nginx:1.15
      depends_on:
      - php
      volumes:
      - document-volume:/var/www/app
      - phpfpm-socket:/var/run
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/log/nginx:/var/log/nginx
      env_file:
      - ./.env.docker
      ports:
      - 8080:80
      - 443:443
      networks:
      - app-network
      command: /bin/sh -c "apt-get update; apt-get install -y vim; nginx -g 'daemon off;' "

   db:
      image: mariadb:10.4
      volumes:
      - ./docker/mysql/init.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/data:/var/lib/mysql
      env_file:
      - ./.env.docker
      ports:
      - 3306:3306
      networks:
      - app-network

   php:
      build:
         args:
            www_user: ${www_user}
            www_password: ${www_password}
            NODE_VERSION: ${NODE_VERSION}
         context: ./docker/php
      volumes:
      - document-volume:/var/www/app:cached
      - phpfpm-socket:/var/run
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      env_file:
      - ./.env.docker
      ports:
      - 9001:9001
      environment:
         TIMEZONE: Asia/Tokyo
         LANGUAGE: "Japanese"
         NVM_DIR:
      tty: true
      networks:
      - app-network

volumes:
   document-volume:
      driver_opts:
         type: none
         o: bind
         device: ${PWD}
   phpfpm-socket:

networks:
   app-network:
